[workspace]
members = ["cloradar-apiserver", "cloradar-registrar", "cloradar-tracker"]

[workspace.package]
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.65"

[workspace.dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
bincode = "1.3.3"
clap = { version = "4.0.22", features = ["derive"] }
config = "0.13.2"
deadpool-postgres = { version = "0.10.3", features = ["serde"] }
futures = "0.3.25"
hex = "0.4.3"
http = "0.2.8"
openssl = { version = "0.10.42", features = ["vendored"] }
postgres-openssl = "0.5.0"
reqwest = "0.11.12"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
serde_yaml = "0.9.14"
sha2 = "0.10.6"
tokio = { version = "1.21.2", features = [
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
    "time",
] }
tokio-postgres = { version = "0.7.7", features = [
    "with-time-0_3",
    "with-serde_json-1",
    "with-uuid-1",
] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
