apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}apiserver-config
type: Opaque
stringData:
  apiserver.yaml: |-
    db:
      host: {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
      port: {{ .Values.db.port }}
      dbname: {{ .Values.db.dbname }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    log:
      format: {{ .Values.log.format }}
    apiserver:
      addr: {{ .Values.apiserver.addr }}
      staticPath: {{ .Values.apiserver.staticPath }}
