[package]
name = "cloradar-tracker"
description = "Process that collects and indexes GitHub issues that meet certain criteria"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
