[package]
name = "cloradar-apiserver"
description = "Server that exposes the CLORadar HTTP API and serves static assets"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
